### ISSUE TITLE
finetune with high resolution input

### ISSUE THREAD

**Issue by baiyang4** [rmaphoh/RETFound_MAE#10]
Hi there,

The defualt input size is 224 * 224 for the model.
I'm wondering if I can fine-tune the model with input image size 384 * 384. How do I modifty the code to implement.

BW

**Comment by rmaphoh** [comment]
Sure. I am currently on leave and will add this function before the end of next week.

**Comment by rmaphoh** [comment]
> Sure. I am currently on leave and will add this function before the end of next week.

The function has been added as a hyperparameter.
