### ISSUE TITLE
Fail to run your visualize

### ISSUE THREAD

**Issue by KevinZ4** [rmaphoh/RETFound_MAE#11]
I try to run the visualize, but with many errors in "Load a pre-trained MAE model" part.

**Comment by rmaphoh** [comment]
Thanks for your interest in RETFound. Can I double-check if you have downloaded the pre-trained model weight from [here](https://github.com/rmaphoh/RETFound_MAE#:~:text=Download%20the%20RETFound%20pre%2Dtrained%20weights)? If so, could you share the error info?

**Comment by rmaphoh** [comment]
close due to no reponse
