### ISSUE TITLE
Pre processing of fine-tuning datasets

### ISSUE THREAD

**Issue by ftimes** [rmaphoh/RETFound_MAE#17]
Hi~Thank you very much for your meaningful work.

I noticed that you mentioned the preprocessing of CFP in "**Data processing and augmentation for SSL**".

I would like to know if this preprocessing still occurs during the fine-tuning stage? Can I request pre processing of relevant manuscripts or processed fine-tuning datasets?

Thank you very much for your help!

**Comment by rmaphoh** [comment]
Thanks. 

Before fine-tuning, the preprocessing for CFP was done with AutoMorph (https://github.com/rmaphoh/AutoMorph). AutoMorph includes four steps (preprocess, quality assessment, segmentation, and feature measurement) and we only use the first step to crop the redundant background and make images square. 

All augmentation and processing for fine-tuning are included in the code (https://github.com/rmaphoh/RETFound_MAE/blob/e5b26cddf1361afd99dee07f5df739130b9e4fb2/util/datasets.py#L21).

**Comment by ftimes** [comment]
Thank you for your prompt reply. I will try again. : -)
