### ISSUE TITLE
fine-tuning weights

### ISSUE THREAD

**Issue by DavinciWu** [rmaphoh/RETFound_MAE#18]
Hi~Thank you very much for your meaningful work.
i don't want to load the pre-training weights, but rather train the model directly from scratch.
how should i to do in the code?(●'◡'●)

**Comment by rmaphoh** [comment]
Thanks for your interest in RETFound. The SSL training script has not been included. We plan to add the relevant scripts and instructions in the next update (hopefully in coming weeks). You can also find similar info in the original MAE (https://github.com/facebookresearch/mae).

**Comment by DavinciWu** [comment]
Thank you for your answer. I am not sure you understood what I meant.
stage1 Self-supervision on retinal images stage2 Supervised fine-tuning for clinical tasks
And now i don't need Fine-tuning with RETFound weights in stage1. Just load the whole model and train it on my dataset from scratch.
As for the SSL training script has not been included.So it has fine-tune train and evaluation scripts and whole model script in the code?

**Comment by rmaphoh** [comment]
Please refer to the explanation of pre-trained weights [here](https://github.com/rmaphoh/RETFound_MAE/issues/19#issuecomment-1833872039). 
If you would like to SSL pre-train from scratch, you can find the SSL training code in the [original MAE](https://github.com/facebookresearch/mae). If you just want to fine-tune the model on your data, follow the [instructions](https://github.com/rmaphoh/RETFound_MAE#fine-tuning-with-retfound-weights)
