### ISSUE TITLE
Splits for OCTID dataset

### ISSUE THREAD

**Issue by TheoPis** [rmaphoh/RETFound_MAE#21]
Thanks for sharing the code/weights of this great work.
I want to compare another model with RETFound's results on OCTID dataset. Could you share the splits used for train/val/test on this dataset, i.e the exact image filenames used per split?

**Comment by rmaphoh** [comment]
Thanks for your interest in RETFound. The data split has been uploaded.

**Comment by TheoPis** [comment]
Many thanks !
