### ISSUE TITLE
How to use multiple GPUs for finetune?

### ISSUE THREAD

**Issue by Akemimadokami** [rmaphoh/RETFound_MAE#4]
I am a greenhand at coding, wondering how to use multiple GPUs for finetune?
I have 4 available GPUs and have set "--world_size" to 4, but it seems there is only 1 GPU being used.

**Comment by rmaphoh** [comment]
Hi there, for multiple GPU training please see the bolded part below (4 GPUs as an example).

**CUDA_VISIBLE_DEVICES=0,1,2,3** python -m torch.distributed.launch **--nproc_per_node=4** --master_port=48798 main_finetune.py \
    --batch_size 16 \
    **--world_size 4** \
    --model vit_large_patch16 \
    --epochs 50 \
    --blr 5e-3 --layer_decay 0.65 \
    --weight_decay 0.05 --drop_path 0.2 \
    --nb_classes 5 \
    --data_path ./IDRiD_data/ \
    --task ./finetune_IDRiD/ \
    --finetune ./RETFound_cfp_weights.pth

**Comment by Akemimadokami** [comment]
Thanks a lot!
