### ISSUE TITLE
Would it be possible to opensource the DINO pretrained weights? 

### ISSUE THREAD

**Issue by krishnaadithya** [rmaphoh/RETFound_MAE#5]
I would really appreciate it if you can open-source the DINO weights, with a contrastive learning-based approach like DINO we can explore unsupervised segmentation.

**Comment by rmaphoh** [comment]
Hi Krishna, thanks for your interest in this work. We are currently working on several projects and therefore have limited bandwidth. We hope to curate and release the contrastive SSL pre-trained models later this year. I will message you when we release them.

**Comment by rmaphoh** [comment]
Will add the news when updated.
