### ISSUE TITLE
How to use this to detect disease? 

### ISSUE THREAD

**Issue by akash769** [rmaphoh/RETFound_MAE#6]
From the point:
`RETFound has been validated in multiple disease detection tasks`

How can i use this repo to detect disease?

**Comment by krishnaadithya** [comment]
You can fintune it on any disease dataset, the instructions for Idrid dataset are on the readme page

**Comment by rmaphoh** [comment]
Hi Akash, we released RETFound as a foundation model which can be fine-tuned to multiple disease detection tasks, with better performance and less data compared to some commonly used pre-trained models. However, fine-tuning is still required for specific disease detection.

**Comment by rmaphoh** [comment]
This issue has been closed due to no further response.
