### ISSUE TITLE
Is it possible to share the dataset used in pretraining

### ISSUE THREAD

**Issue by AlanZhang1995** [rmaphoh/RETFound_MAE#7]
> The Moorfields diabetic image dataset (MEH-MIDAS) and public data (totalling 904,170 CFPs and 736,442 OCTs).

This dataset with 1.6 million samples will have significant impact if it is publicly available, I believe!

**Comment by AlanZhang1995** [comment]
I found information in paper. Thanks for your good work!

**Comment by RoyH11** [comment]
So was this Moorfields diabetic image dataset not public?
